[build]
  # No build command needed - serving static files
  publish = "."



# Optional: keep the SPA-style catch-all you already had
[[redirects]]
  from = "/*"
  to   = "/index.html"
  status = 200


[build.environment]
PYTHON_VERSION = "3.11"