[build]
  command = """
    python -m ensurepip --upgrade
    python -m pip install --upgrade pip
    python -m pip install pygbag pygame
    # --archive creates build/web/archives/… with the wheels inside
    python -m pygbag --archive awesome --build game.py
  """
  publish = "build/web"



# Optional: keep the SPA-style catch-all you already had
[[redirects]]
  from = "/*"
  to   = "/index.html"
  status = 200


[build.environment]
PYTHON_VERSION = "3.11"